<?php

declare(strict_types=1);

/**
 * OAuth/OIDC provider presets for well-known providers.
 *
 * Each entry pre-populates endpoints, scopes, and display metadata so an admin
 * only needs to add their client_id and client_secret.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/horde/oauth_presets.local.php or
 * var/config/horde/oauth_presets.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/horde/oauth_presets-servername.php.
 *
 * Keys are provider_id slugs (lowercase, [a-z0-9_-]).
 *
 * Fields:
 *   name                     – Human-readable provider name
 *   type                     – 'oauth2' | 'oidc'
 *   issuer                   – Issuer URL (OIDC providers use this for auto-discovery)
 *   authorization_endpoint   – OAuth2 authorization URL
 *   token_endpoint           – Token exchange URL
 *   userinfo_endpoint        – User info / profile URL
 *   jwks_uri                 – JSON Web Key Set URL (OIDC)
 *   revocation_endpoint      – Token revocation URL (optional)
 *   default_scopes           – Space-separated scopes for initial login/connect
 *   display                  – Persisted on creation as display_label, display_icon, display_color
 *   notes                    – Shown in admin UI; not persisted
 *
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category Horde
 * @package  Horde
 * @author   Ralf Lang <ralf.lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */

$backends['github'] = [
    'name' => 'GitHub',
    'type' => 'oauth2',
    'issuer' => 'https://github.com',
    'authorization_endpoint' => 'https://github.com/login/oauth/authorize',
    'token_endpoint' => 'https://github.com/login/oauth/access_token',
    'userinfo_endpoint' => 'https://api.github.com/user',
    'default_scopes' => 'read:user user:email',
    'display' => [
        'label' => 'GitHub',
        'icon' => 'github',
        'color' => '#24292e',
    ],
    'notes' => 'Register an OAuth App at https://github.com/settings/developers. Set the callback URL to your Horde\'s /settings/oauth/callback.',
];

$backends['google'] = [
    'name' => 'Google',
    'type' => 'oidc',
    'issuer' => 'https://accounts.google.com',
    'authorization_endpoint' => 'https://accounts.google.com/o/oauth2/v2/auth',
    'token_endpoint' => 'https://oauth2.googleapis.com/token',
    'userinfo_endpoint' => 'https://openidconnect.googleapis.com/v1/userinfo',
    'jwks_uri' => 'https://www.googleapis.com/oauth2/v3/certs',
    'revocation_endpoint' => 'https://oauth2.googleapis.com/revoke',
    'default_scopes' => 'openid email profile',
    'display' => [
        'label' => 'Google',
        'icon' => 'google',
        'color' => '#4285f4',
    ],
    'notes' => 'Create OAuth credentials at https://console.cloud.google.com/apis/credentials. Enable the "Google Identity" API.',
];

$backends['microsoft'] = [
    'name' => 'Microsoft',
    'type' => 'oidc',
    'issuer' => 'https://login.microsoftonline.com/common/v2.0',
    'authorization_endpoint' => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    'token_endpoint' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    'userinfo_endpoint' => 'https://graph.microsoft.com/oidc/userinfo',
    'jwks_uri' => 'https://login.microsoftonline.com/common/discovery/v2.0/keys',
    'default_scopes' => 'openid email profile',
    'display' => [
        'label' => 'Microsoft',
        'icon' => 'microsoft',
        'color' => '#00a4ef',
    ],
    'notes' => 'Register an app at https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps. Use "common" tenant for multi-tenant or replace with your tenant ID.',
];

$backends['apple'] = [
    'name' => 'Apple',
    'type' => 'oidc',
    'issuer' => 'https://appleid.apple.com',
    'authorization_endpoint' => 'https://appleid.apple.com/auth/authorize',
    'token_endpoint' => 'https://appleid.apple.com/auth/token',
    'jwks_uri' => 'https://appleid.apple.com/auth/keys',
    'default_scopes' => 'openid email name',
    'display' => [
        'label' => 'Apple',
        'icon' => 'apple',
        'color' => '#000000',
    ],
    'notes' => 'Configure Sign in with Apple at https://developer.apple.com/account/resources/identifiers. Requires Apple Developer Program membership.',
];

$backends['gitlab'] = [
    'name' => 'GitLab',
    'type' => 'oidc',
    'issuer' => 'https://gitlab.com',
    'authorization_endpoint' => 'https://gitlab.com/oauth/authorize',
    'token_endpoint' => 'https://gitlab.com/oauth/token',
    'userinfo_endpoint' => 'https://gitlab.com/oauth/userinfo',
    'jwks_uri' => 'https://gitlab.com/oauth/discovery/keys',
    'revocation_endpoint' => 'https://gitlab.com/oauth/revoke',
    'default_scopes' => 'openid email profile',
    'display' => [
        'label' => 'GitLab',
        'icon' => 'gitlab',
        'color' => '#fc6d26',
    ],
    'notes' => 'Create an application at https://gitlab.com/-/user_settings/applications. For self-hosted GitLab, change the issuer URL.',
];

$backends['mastodon'] = [
    'name' => 'PHPC Mastodon',
    'type' => 'oauth2',
    'issuer' => 'https://phpc.social',
    'authorization_endpoint' => 'https://phpc.social/oauth/authorize',
    'token_endpoint' => 'https://phpc.social/oauth/token',
    'userinfo_endpoint' => 'https://phpc.social/api/v1/accounts/verify_credentials',
    'revocation_endpoint' => 'https://phpc.social/oauth/revoke',
    'default_scopes' => 'read:accounts',
    'display' => [
        'label' => 'PHPC Mastodon',
        'icon' => 'mastodon',
        'color' => '#6364ff',
    ],
    'notes' => 'Register an application at https://phpc.social/settings/applications. Replace the default Redirect URI (urn:ietf:wg:oauth:2.0:oob) with the callback URL shown below. Any Mastodon instance uses the same endpoint pattern.',
];

$backends['x'] = [
    'name' => 'X (Twitter)',
    'type' => 'oauth2',
    'issuer' => 'https://x.com',
    'authorization_endpoint' => 'https://x.com/i/oauth2/authorize',
    'token_endpoint' => 'https://api.x.com/2/oauth2/token',
    'userinfo_endpoint' => 'https://api.x.com/2/users/me',
    'revocation_endpoint' => 'https://api.x.com/2/oauth2/revoke',
    'default_scopes' => 'tweet.read users.read offline.access',
    'display' => [
        'label' => 'X',
        'icon' => 'twitter',
        'color' => '#000000',
    ],
    'notes' => 'Create a project and app at https://developer.x.com/. Enable OAuth 2.0 with PKCE. Apps may request additional scopes (e.g. tweet.write) via incremental consent when needed.',
];

$backends['facebook'] = [
    'name' => 'Facebook',
    'type' => 'oauth2',
    'issuer' => 'https://www.facebook.com',
    'authorization_endpoint' => 'https://www.facebook.com/v21.0/dialog/oauth',
    'token_endpoint' => 'https://graph.facebook.com/v21.0/oauth/access_token',
    'userinfo_endpoint' => 'https://graph.facebook.com/v21.0/me?fields=id,name,email',
    'default_scopes' => 'public_profile email',
    'display' => [
        'label' => 'Facebook',
        'icon' => 'facebook',
        'color' => '#1877f2',
    ],
    'notes' => 'Create an app at https://developers.facebook.com/apps. Add "Facebook Login" product and configure the redirect URI.',
];

$backends['nextcloud'] = [
    'name' => 'Nextcloud',
    'type' => 'oidc',
    'issuer' => '',
    'authorization_endpoint' => '',
    'token_endpoint' => '',
    'userinfo_endpoint' => '',
    'default_scopes' => 'openid email profile',
    'display' => [
        'label' => 'Nextcloud',
        'icon' => 'nextcloud',
        'color' => '#0082c9',
    ],
    'notes' => 'Set the issuer to your Nextcloud URL (e.g. https://cloud.example.com). Requires the "OIDC Identity Provider" app. Endpoints will be auto-discovered.',
];
