<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/horde/routes.local.php and run composer horde:reconfigure
namespace Horde\Horde;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes - Phase 0: Login
$mapper->connect(
    'ResponsiveLogin',
    '/auth/login',
    [
        'controller' => Auth\ResponsiveLoginController::class,
        'HordeAuthType' => 'NONE',
        'stack' => [],
    ]
);

// Responsive logout - clean endpoint without tokens
$mapper->connect(
    'ResponsiveLogout',
    '/auth/logout',
    [
        'controller' => Auth\ResponsiveLogoutController::class,
        'HordeAuthType' => 'authenticate', // Must be authenticated to logout
        'stack' => [],
    ]
);

// Responsive UI Routes - Phase 1: Portal
$mapper->connect(
    'ResponsivePortal',
    '/portal/',
    [
        'controller' => Portal\ResponsivePortalController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

// Smartmobile alias - forwards to responsive portal
// This route will become active once services/portal/smartmobile.php is deleted
$mapper->connect(
    'SmartmobilePortalAlias',
    '/services/portal/smartmobile.php',
    [
        'controller' => Portal\ResponsivePortalController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

// Authentication API Routes
$mapper->connect(
    'AuthApiLogin',
    '/api/v1/auth/login',
    [
        'controller' => Auth\AuthApiController::class,
        'HordeAuthType' => 'NONE',
        'stack' => [\Horde\Http\Server\Middleware\JsonBodyParser::class],
    ]
);

// Dual-mode refresh endpoint:
// - With refresh_token: Standard JWT refresh
// - Without refresh_token: Bootstrap JWT from session (for old login.php users)
$mapper->connect(
    'AuthApiRefresh',
    '/api/v1/auth/refresh',
    [
        'controller' => Auth\AuthApiController::class,
        'HordeAuthType' => 'NONE', // Auth checked inside controller
        'stack' => [\Horde\Http\Server\Middleware\JsonBodyParser::class],
    ]
);

$mapper->connect(
    'AuthApiLogout',
    '/api/v1/auth/logout',
    [
        'controller' => Auth\AuthApiController::class,
        'HordeAuthType' => 'NONE',
        'stack' => [],
    ]
);

// Preliminary implementation of a readiness check route. Just returns body "1"
$mapper->connect(
    'Readiness',
    '/observability/readiness',
    [
        'controller' => Observability\Readiness::class,
        // Override this in routes.local.php if you don't want to expose this unautenticated
        'HordeAuthType' => 'NONE',
    ]
);
