<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/horde/routes.local.php and run composer horde:reconfigure

namespace Horde\Horde;

use Horde\Core\Middleware\AuthHordeSession;
use Horde\Core\Middleware\AuthIsGlobalAdmin;
use Horde\Core\Middleware\ConditionalCsrfMiddleware;
use Horde\Core\Middleware\DefaultStack;
use Horde\Core\Middleware\DemandAuthenticatedUser;
use Horde\Core\Middleware\DemandGlobalAdmin;
use Horde\Core\Middleware\ErrorFilter;
use Horde\Core\Middleware\HordeCore;
use Horde\Core\Middleware\JwtAuthMiddleware;
use Horde\Core\Middleware\OAuthConsentMiddleware;
use Horde\Http\Server\Middleware\JsonBodyParser;
use Horde\OAuth\Oidc\Handler\DiscoveryEndpoint;
use Horde\OAuth\Oidc\Handler\JwksEndpoint;
use Horde\OAuth\Oidc\Handler\UserinfoEndpoint;
use Horde\OAuth\Server\Handler\AuthorizationEndpoint;
use Horde\OAuth\Server\Handler\IntrospectionEndpoint;
use Horde\OAuth\Server\Handler\RevocationEndpoint;
use Horde\OAuth\Server\Handler\TokenEndpoint;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes - Phase 0: Login
$mapper->buildRoute(uri: '/auth/login', name: 'ResponsiveLogin')
    ->withController(Auth\ResponsiveLoginController::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([AuthHordeSession::class])
    ->add();

// Responsive logout - clean endpoint without tokens
$mapper->buildRoute(uri: '/auth/logout', name: 'ResponsiveLogout')
    ->withController(Auth\ResponsiveLogoutController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate']) // Must be authenticated to logout
    ->withMiddleware(DefaultStack::get())
    ->add();

// OAuth/OIDC Login — initiate login via external provider (unauthenticated)
$mapper->buildRoute(uri: '/auth/oauth/login/:providerId', name: 'OAuthLogin')
    ->withController(Auth\OAuthLoginController::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([AuthHordeSession::class])
    ->withMethods(['POST'])
    ->add();

// Responsive UI Routes - Phase 1: Portal
$mapper->buildRoute(uri: '/portal/', name: 'ResponsivePortal')
    ->withController(Portal\ResponsivePortalController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/services/portal/smartmobile.php')
    ->add();

// Responsive Admin Dashboard
$mapper->buildRoute(uri: '/admin/', name: 'AdminDashboard')
    ->withController(Admin\AdminDashboardController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware([HordeCore::class, ErrorFilter::class, AuthHordeSession::class, DemandAuthenticatedUser::class])
    ->withMethods(['GET'])
    ->add();

// Authentication API Routes
$mapper->buildRoute(uri: '/api/v1/auth/login', name: 'AuthApiLogin')
    ->withController(Auth\AuthApiController::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

// Dual-mode refresh endpoint:
// - With refresh_token: Standard JWT refresh
// - Without refresh_token: Bootstrap JWT from session (for old login.php users)
$mapper->buildRoute(uri: '/api/v1/auth/refresh', name: 'AuthApiRefresh')
    ->withController(Auth\AuthApiController::class)
    ->withDefaults(['HordeAuthType' => 'NONE']) // Auth checked inside controller
    ->withMiddleware([JsonBodyParser::class])
    ->add();

$mapper->buildRoute(uri: '/api/v1/auth/logout', name: 'AuthApiLogout')
    ->withController(Auth\AuthApiController::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->noMiddleware()
    ->add();

// Preliminary implementation of a readiness check route. Just returns body "1"
// Readiness is PSR-15 middleware that terminates the chain by returning a
// response directly, so it goes in the middleware stack with no controller.
$mapper->buildRoute(uri: '/observability/readiness', name: 'Readiness')
    // Override this in routes.local.php if you don't want to expose this unautenticated
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([Observability\Readiness::class])
    ->add();

// Admin API Routes - Introspection
$mapper->buildRoute(uri: '/api/v1/admin/info', name: 'AdminApiInfo')
    ->withController(Admin\AdminApiController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'info'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/applications', name: 'AdminApiApplications')
    ->withController(Admin\AdminApiController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'applications'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

// Admin API Routes - Users
$mapper->buildRoute(uri: '/api/v1/admin/users', name: 'AdminApiUserList')
    ->withController(Admin\UserController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'list'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/users', name: 'AdminApiUserCreate')
    ->withController(Admin\UserController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'create'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/users/:username', name: 'AdminApiUser')
    ->withController(Admin\UserController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'get'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/users/:username', name: 'AdminApiUserDelete')
    ->withController(Admin\UserController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'delete'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['DELETE'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/users/:username/password', name: 'AdminApiUserPassword')
    ->withController(Admin\UserController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'updatePassword'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

// Admin API Routes - Identities (first-class resource)
$mapper->buildRoute(uri: '/api/v1/admin/identities/:username', name: 'AdminApiIdentityList')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'list'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/identities/:username', name: 'AdminApiIdentityCreate')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'create'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/identities/:username/:index', name: 'AdminApiIdentityGet')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'get'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/identities/:username/:index', name: 'AdminApiIdentityUpdate')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'update'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['PUT', 'PATCH'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/identities/:username/:index', name: 'AdminApiIdentityDelete')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'delete'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['DELETE'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/identities/:username/:index/default', name: 'AdminApiIdentitySetDefault')
    ->withController(Admin\IdentityController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'setDefault'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['PATCH'])
    ->add();

// Group Management API Routes
$mapper->buildRoute(uri: '/api/v1/admin/groups', name: 'AdminApiGroupCreate')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'create'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups', name: 'AdminApiGroupList')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'list'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier', name: 'AdminApiGroupDelete')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'delete'])
    ->withMethods(['DELETE'])
    ->noMiddleware()
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier', name: 'AdminApiGroupGet')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'get'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier/members', name: 'AdminApiGroupMembersAdd')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'addMember'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier/members', name: 'AdminApiGroupMembersSet')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'setMembers'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['PUT'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier/members', name: 'AdminApiGroupMembersList')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'getMembers'])
    ->withMiddleware([JsonBodyParser::class])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/groups/:identifier/members/:username', name: 'AdminApiGroupMembersRemove')
    ->withController(Admin\GroupController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'removeMember'])
    ->withMethods(['DELETE'])
    ->add();

// Permission Management API Routes
$mapper->buildRoute(uri: '/api/v1/admin/permissions', name: 'AdminApiPermissionList')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'list'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/permissions', name: 'AdminApiPermissionCreate')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'create'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/permissions/:name', name: 'AdminApiPermissionGet')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'get'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/permissions/:name', name: 'AdminApiPermissionUpdate')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'update'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['PATCH'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/permissions/:name', name: 'AdminApiPermissionDelete')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'delete'])
    ->withMethods(['DELETE'])
    ->noMiddleware()
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/permissions/:name/parents', name: 'AdminApiPermissionGetParents')
    ->withController(Admin\PermissionController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'action' => 'getParents'])
    ->withMiddleware([JsonBodyParser::class])
    ->withMethods(['GET'])
    ->add();

// Health Check API Routes
$mapper->buildRoute(uri: '/api/v1/admin/health/:subsystem', name: 'AdminApiHealthCheck')
    ->withController(Admin\HealthCheckController::class)
    ->withDefaults(['HordeAuthType' => 'NONE', 'subsystem' => 'all'])
    ->withMethods(['GET'])
    ->noMiddleware()
    ->add();

// Admin API Routes - OAuth Key Management
$mapper->buildRoute(uri: '/api/v1/admin/oauth/signing-key', name: 'AdminApiOAuthSigningKey')
    ->withController(Admin\OAuthKeyController::class)
    ->withDefaults(['action' => 'signing_key'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/api/v1/admin/oauth/jwt-secret', name: 'AdminApiOAuthJwtSecret')
    ->withController(Admin\OAuthKeyController::class)
    ->withDefaults(['action' => 'jwt_secret'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['POST'])
    ->add();

// Admin HTML Routes - API Registry
$mapper->buildRoute(uri: '/admin/apis/', name: 'AdminApiRegistry')
    ->withController(Admin\ApiRegistryController::class)
    ->withDefaults(['action' => 'list'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['GET'])
    ->add();

// Admin HTML Routes - Authentication System Status
$mapper->buildRoute(uri: '/admin/authentication/status/', name: 'AdminAuthStatus')
    ->withController(Admin\OAuthSystemStatusController::class)
    ->withDefaults(['action' => 'status'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['GET'])
    ->add();

// Admin HTML Routes - OAuth Provider Management
$mapper->buildRoute(uri: '/admin/authentication/provider/', name: 'AdminProviderList')
    ->withController(Admin\OAuthProviderController::class)
    ->withDefaults(['action' => 'list'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/admin/authentication/provider/', name: 'AdminProviderCreate')
    ->withController(Admin\OAuthProviderController::class)
    ->withDefaults(['action' => 'create'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/admin/authentication/provider/:providerId', name: 'AdminProviderEdit')
    ->withController(Admin\OAuthProviderController::class)
    ->withDefaults(['action' => 'edit'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/admin/authentication/provider/:providerId', name: 'AdminProviderUpdate')
    ->withController(Admin\OAuthProviderController::class)
    ->withDefaults(['action' => 'update'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/admin/authentication/provider/:providerId/delete', name: 'AdminProviderDelete')
    ->withController(Admin\OAuthProviderController::class)
    ->withDefaults(['action' => 'delete'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        AuthIsGlobalAdmin::class,
        DemandAuthenticatedUser::class,
        DemandGlobalAdmin::class,
    ])
    ->withMethods(['POST'])
    ->add();

// User Settings Routes - OAuth Connected Accounts
$mapper->buildRoute(uri: '/settings/oauth/', name: 'SettingsOAuthList')
    ->withController(Settings\OAuthAccountController::class)
    ->withDefaults(['action' => 'list'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        DemandAuthenticatedUser::class,
    ])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/settings/oauth/connect/:providerId', name: 'SettingsOAuthConnect')
    ->withController(Settings\OAuthAccountController::class)
    ->withDefaults(['action' => 'connect'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        DemandAuthenticatedUser::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/settings/oauth/callback', name: 'SettingsOAuthCallback')
    ->withController(Settings\OAuthAccountController::class)
    ->withDefaults(['action' => 'callback'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
    ])
    ->withMethods(['GET'])
    ->add();

$mapper->buildRoute(uri: '/settings/oauth/disconnect/:providerId', name: 'SettingsOAuthDisconnect')
    ->withController(Settings\OAuthAccountController::class)
    ->withDefaults(['action' => 'disconnect'])
    ->withMiddleware([
        HordeCore::class,
        ErrorFilter::class,
        AuthHordeSession::class,
        DemandAuthenticatedUser::class,
    ])
    ->withMethods(['POST'])
    ->add();

// OAuth2 Server Endpoints
$mapper->buildRoute(uri: '/oauth2/authorize', name: 'OAuthAuthorize')
    ->withController(AuthorizationEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware([
        AuthHordeSession::class,
        OAuthConsentMiddleware::class,
    ])
    ->withMethods(['GET', 'POST'])
    ->add();

$mapper->buildRoute(uri: '/oauth2/token', name: 'OAuthToken')
    ->withController(TokenEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([
        JsonBodyParser::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/oauth2/revoke', name: 'OAuthRevoke')
    ->withController(RevocationEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([
        JsonBodyParser::class,
    ])
    ->withMethods(['POST'])
    ->add();

$mapper->buildRoute(uri: '/oauth2/introspect', name: 'OAuthIntrospect')
    ->withController(IntrospectionEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([
        JsonBodyParser::class,
    ])
    ->withMethods(['POST'])
    ->add();

// OIDC Endpoints
$mapper->buildRoute(uri: '/.well-known/openid-configuration', name: 'OidcDiscovery')
    ->withController(DiscoveryEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMethods(['GET'])
    ->noMiddleware()
    ->add();

$mapper->buildRoute(uri: '/oauth2/userinfo', name: 'OidcUserinfo')
    ->withController(UserinfoEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMiddleware([
        JwtAuthMiddleware::class,
    ])
    ->withMethods(['GET', 'POST'])
    ->add();

$mapper->buildRoute(uri: '/.well-known/jwks.json', name: 'OidcJwks')
    ->withController(JwksEndpoint::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->withMethods(['GET'])
    ->noMiddleware()
    ->add();

// AJAX Dispatch Routes
// Two-form: legacy URL pattern (app/action), session auth only.
// When traffic goes through the router (responsive UI), this replaces
// the direct hit to services/ajax.php. Legacy Horde::url() direct
// script hits still go to services/ajax.php — no behavioral change.
$mapper->buildRoute(uri: '/services/ajax.php/:app/:action', name: 'AjaxDispatchLegacy')
    ->withController(AjaxDispatchController::class)
    ->withMiddleware([
        AuthHordeSession::class,
    ])
    ->withMethods(['GET', 'POST'])
    ->add();

// Three-form: explicit interface.method addressing (new URL pattern).
// Nothing calls this yet — purely additive. Intended for direct
// ApiRegistry dispatch with dual auth (JWT + session).
$mapper->buildRoute(uri: '/services/ajax.php/:app/ajax/:qualifiedMethod', name: 'AjaxDispatchModern')
    ->withController(AjaxDispatchController::class)
    ->withMiddleware([
        JwtAuthMiddleware::class,
        AuthHordeSession::class,
        DemandAuthenticatedUser::class,
        ConditionalCsrfMiddleware::class,
    ])
    ->withMethods(['GET', 'POST'])
    ->add();

// Download service route for routed (Rampage) requests.
// Keeps classic /services/download/ query contract (app, fn, token, ...).
$mapper->buildRoute(uri: '/services/download/', name: 'DownloadService')
    ->withController(DownloadController::class)
    ->withDefaults(['HordeAuthType' => 'NONE'])
    ->noMiddleware()
    ->withSecondaryRoute('/services/download')
    ->withMethods(['GET', 'POST'])
    ->add();
