<?php

declare(strict_types=1);

/**
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category Horde
 * @package  Horde
 * @author   Ralf Lang <ralf.lang@ralf-lang.de>
 * @license  http://www.horde.org/licenses/lgpl21 LGPL 2.1
 */

namespace Horde\Horde\Admin;

use Horde\Exception\HordeRuntimeException;
use Horde\Horde\Service\CryptoKeyManager;
use Horde\Horde\Traits\JsonResponseTrait;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Throwable;

class OAuthKeyController implements RequestHandlerInterface
{
    use JsonResponseTrait;

    private const DEFAULT_SIGNING_KEY = 'horde/oauth2.pem';
    private const DEFAULT_JWT_SECRET = 'horde/jwt.secret';

    public function __construct(
        private readonly CryptoKeyManager $keyManager,
    ) {}

    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        $route = $request->getAttribute('route') ?? [];
        $action = $route['action'] ?? '';

        return match ($action) {
            'signing_key' => $this->generateSigningKey(),
            'jwt_secret' => $this->generateJwtSecret(),
            default => $this->jsonError('Unknown action', 404),
        };
    }

    private function generateSigningKey(): ResponseInterface
    {
        $conf = $GLOBALS['conf'] ?? [];
        $path = $conf['oauth_server']['private_key_file'] ?? '';

        if ($path === '') {
            $path = self::DEFAULT_SIGNING_KEY;
            try {
                $this->writeConfSnippet('oauth_server_key.php', [
                    'oauth_server' => ['private_key_file' => $path],
                ]);
            } catch (Throwable $e) {
                return $this->jsonError('Failed to write config: ' . $e->getMessage(), 500);
            }
        }

        $path = $this->resolvePath($path);

        try {
            $this->keyManager->ensureRsaKeyExists($path);
        } catch (Throwable $e) {
            return $this->jsonError($e->getMessage(), 500);
        }

        return $this->jsonResponse([
            'status' => 'ok',
            'path' => $path,
        ]);
    }

    private function generateJwtSecret(): ResponseInterface
    {
        $conf = $GLOBALS['conf'] ?? [];
        $path = $conf['auth']['jwt']['secret_file'] ?? '';

        if ($path === '') {
            $path = self::DEFAULT_JWT_SECRET;
            try {
                $this->writeConfSnippet('jwt_secret.php', [
                    'auth' => ['jwt' => ['secret_file' => $path]],
                ]);
            } catch (Throwable $e) {
                return $this->jsonError('Failed to write config: ' . $e->getMessage(), 500);
            }
        }

        $path = $this->resolvePath($path);

        try {
            $this->keyManager->ensureSecretExists($path);
        } catch (Throwable $e) {
            return $this->jsonError($e->getMessage(), 500);
        }

        return $this->jsonResponse([
            'status' => 'ok',
            'path' => $path,
        ]);
    }

    private function resolvePath(string $path): string
    {
        if (!str_starts_with($path, '/') && defined('HORDE_CONFIG_BASE')) {
            return HORDE_CONFIG_BASE . '/' . $path;
        }

        return $path;
    }

    private function writeConfSnippet(string $filename, array $conf): void
    {
        if (!defined('HORDE_CONFIG_BASE')) {
            throw new HordeRuntimeException('HORDE_CONFIG_BASE is not defined.');
        }

        $dir = HORDE_CONFIG_BASE . '/horde/conf.d';
        if (!is_dir($dir) && !mkdir($dir, 0o750, true)) {
            throw new HordeRuntimeException("Cannot create directory: {$dir}");
        }

        $content = "<?php\n"
            . "// Auto-generated by Horde OAuth admin\n"
            . $this->exportArray($conf, '$conf');

        $path = $dir . '/' . $filename;
        if (file_put_contents($path, $content, LOCK_EX) === false) {
            throw new HordeRuntimeException("Failed to write: {$path}");
        }

        chmod($path, 0o640);
    }

    private function exportArray(array $array, string $prefix, string $output = ''): string
    {
        foreach ($array as $key => $value) {
            $currentKey = $prefix . "['" . addslashes((string) $key) . "']";
            if (is_array($value)) {
                $output = $this->exportArray($value, $currentKey, $output);
            } else {
                $output .= $currentKey . ' = ' . var_export($value, true) . ";\n";
            }
        }

        return $output;
    }
}
